# Generated by Django 4.0 on 2022-01-13 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Studnet',
            new_name='Student',
        ),
    ]
