# Generated by Django 4.0 on 2022-01-17 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0003_remove_questionregister_option1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='marks',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
    ]
