# Generated by Django 4.0 on 2022-01-17 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0004_student_marks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='marks',
        ),
        migrations.AddField(
            model_name='student',
            name='stu_marks',
            field=models.IntegerField(default=0),
        ),
    ]
