# Generated by Django 4.0 on 2022-01-18 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0005_remove_student_marks_student_stu_marks'),
    ]

    operations = [
        migrations.CreateModel(
            name='JavaQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=200)),
                ('Option1', models.CharField(max_length=100)),
                ('Option2', models.CharField(max_length=100)),
                ('Option3', models.CharField(max_length=100)),
                ('Option4', models.CharField(max_length=100)),
                ('Corrans', models.CharField(max_length=100)),
                ('Marks', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='PhpQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=200)),
                ('Option1', models.CharField(max_length=100)),
                ('Option2', models.CharField(max_length=100)),
                ('Option3', models.CharField(max_length=100)),
                ('Option4', models.CharField(max_length=100)),
                ('Corrans', models.CharField(max_length=100)),
                ('Marks', models.IntegerField(default=1)),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='stu_marks_java',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='student',
            name='stu_marks_php',
            field=models.IntegerField(default=0),
        ),
    ]
