# Generated by Django 4.0 on 2022-01-18 07:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0006_javaquestion_phpquestion_student_stu_marks_java_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=200)),
                ('Option1', models.CharField(max_length=100)),
                ('Option2', models.CharField(max_length=100)),
                ('Option3', models.CharField(max_length=100)),
                ('Option4', models.CharField(max_length=100)),
                ('Corrans', models.CharField(max_length=100)),
                ('Marks', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subname', models.CharField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='JavaQuestion',
        ),
        migrations.DeleteModel(
            name='PhpQuestion',
        ),
        migrations.DeleteModel(
            name='QuestionRegister',
        ),
        migrations.AddField(
            model_name='question',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enroll.subject'),
        ),
    ]
